### ISSUE TITLE
Unable to add new chain. Get Invalid Rest URL error

### ISSUE THREAD

**Issue by ramilexe** [cosmostation/cosmostation-chrome-extension#167]
In this [PR](https://github.com/cosmostation/cosmostation-chrome-extension/pull/138) API URI has changed from `/node_info` to `/cosmos/base/tendermint/v1beta1/node_info` but new endpoint returns `default_node_info` object instead of `node_info`.

https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/base/tendermint/v1beta1/query.proto#L139

![image](https://user-images.githubusercontent.com/1008882/230364438-2cabe10a-15e8-4472-8b39-64f023d1557b.png)

Because of that, when we try to add a new cosmos chain, we get error `Invalid Rest URL`

**Comment by ong-ar** [comment]
We will fix it in the next version. thx!
