### ISSUE TITLE
IBC transfer doesn't include newly registered NEOK token

### ISSUE THREAD

**Issue by vrde** [cosmostation/cosmostation-chrome-extension#182]
:wave: hi there, we are trying to transfer our newly registered NEOK IBC coin to Crescent.

Here is a list of all things I've done in the last days, including the registration of our ERC-20 token as an IBC token, please check it out to have better context of my issue: https://github.com/NeokingdomDAO/contracts/issues/38

Our token shows up in the browser extension (see NEOK at the bottom of the screenshot):

![image](https://github.com/cosmostation/cosmostation-chrome-extension/assets/134680/9869b65b-a2b7-4800-89ae-6c1dcb0889f9)

But it doesn't when I try to do an IBC transfer:

![image](https://github.com/cosmostation/cosmostation-chrome-extension/assets/134680/efdae0d6-ae1c-43d7-a146-ac0a27161c56)

How can I transfer the NEOK token using an IBC transfer?

**Comment by vrde** [comment]
@ong-ar @G-Gamja is there any update on this? Unfortunately this is blocking us from moving our IBC coin to Crescent.

**Comment by jeongeunlee1209** [comment]
@vrde Hello, hope you are doing well.
If you would like to send NEOK token to the Crescent, please contact the Crescent Network team to add the token onto the Crescent dApp. After NEOK token being added to the Crescent dApp and able to successfully send the NEOK token to the Crescent network, please submit a PR to the following json file.
https://github.com/cosmostation/chainlist/blob/main/chain/crescent/assets.json

If you have any further questions, please feel free to send an email to support@cosmostation.io.
