### ISSUE TITLE
The extension not working well in extension supporting mobile browser

### ISSUE THREAD

**Issue by freshlife001** [cosmostation/cosmostation-chrome-extension#189]
### Describe the bug
When running in Extension enabled mobile browser like Mises Browser, after user installed the extension, the welcome tabs keeps popping out, and user will unable to proceed.
The bug is caused by a hardcoded check 'window.outerWidth < 450' in many place of the codebase. In pc only popup window width could be less than 450, but this is not true on mobile devices. 
A simple solution is skiping this check on Android.

### Steps to reproduce
install cosmostation in Mises Browser
and this page keeps popping "chrome-extension://fpkhgmpbidmiogeglndfbkegfdlnajnf/popup.html#/account/initialize/welcome"
and the browser not responding anymore 

### Error messages or log output
No response

### Version
0.6.2

### Build type
None

### Browser
Other (please elaborate in the "Additional Context" section)

### Operating system
Other (please elaborate in the "Additional Context" section)

### Hardware wallet
No response

### Additional context
Browser: Mises Browser
OS: Android

**Comment by ong-ar** [comment]
I'm looking for a way to accurately distinguish between window and tab in the chrome extension api. Since the ledger does not work in the popup state, it was temporarily changed to tab. This will be corrected at a later date.

**Comment by freshlife001** [comment]
Yes, using chrome extension api is a better way. BTW,  in Mises Browser, ledger works in any tabs.

**Comment by ong-ar** [comment]
https://github.com/cosmostation/cosmostation-chrome-extension/pull/190

It will be applied to version 0.6.4.
