### ISSUE TITLE
EVM network addr gen issue

### ISSUE THREAD

**Issue by bxlkm** [cosmostation/cosmostation-chrome-extension#202]
evm network coin default is 
bip44: {
    purpose: "44'",
    coinType: "60'",
    account: "0'",
    change: '0',
  },
but okc is "m/44'/996'/0'/0/0"; kava is "m/44'/459'/0'/0/0" 。

Is the evm generated address correct ？

**Comment by ong-ar** [comment]
yes. all of evm networks is 60' coin type.

If you want a `459'` address, use Cosmos Ecosystem KAVA.

`m/44'/996'/0'/0/0` is not supported

**Comment by ong-ar** [comment]
After creating a private key using `459' / 996'`, you can import an account using private key and use it in the evm network.
