### ISSUE TITLE
Connected event

### ISSUE THREAD

**Issue by Wgil** [cosmostation/cosmostation-chrome-extension#231]
Dear cosmostation team,

I am building a Dapp to connect to a custom Cosmos chain and I would like to know if there is an event to detect if the user connects/disconnects to the application through the extension directly without interacting with the Dapp. I tried with the only event available (accountChanged) but it only works when the user changes the account. 

Any help would be appreciated.

**Comment by Wgil** [comment]
I would also need the same for disconnection.

**Comment by ong-ar** [comment]
@Wgil 

When requesting an account, a new pop-up window will appear allowing the user to connect to the Dapp.
In the case of disconnection, the way the user can know can be checked by extension.

![스크린샷 2023-08-11 오후 12 25 43](https://github.com/cosmostation/cosmostation-chrome-extension/assets/5284226/b4f9cd26-f733-4771-96c1-0c52d2ce55bb)

![스크린샷 2023-08-11 오후 12 24 43](https://github.com/cosmostation/cosmostation-chrome-extension/assets/5284226/e009c22a-53bf-499b-9494-94238f0a5919)

![스크린샷 2023-08-11 오후 12 24 49](https://github.com/cosmostation/cosmostation-chrome-extension/assets/5284226/8e902067-0ca0-4b36-a5b0-f4fe764f3ea9)
