### ISSUE TITLE
Extend cosmos events

### ISSUE THREAD

**Issue by Wgil** [cosmostation/cosmostation-chrome-extension#232]
As mentioned in https://github.com/cosmostation/cosmostation-chrome-extension/issues/231 I need `connected` and `disconnected` events to detect on my Dapp if user connects or disconnects their wallet from the browser extension. For what I an see in this code, this functionality it's not implemented yet:

https://github.com/cosmostation/cosmostation-chrome-extension/blob/develop/src/constants/message/index.ts#L10

Is there any way you guys can consider implementing this features please?

Thanks for your attention.

**Comment by ong-ar** [comment]
Thank you for sharing a good idea. However, we currently don't have any plans to develop that feature, but we will review it internally.
