### ISSUE TITLE
cosmostation unstaking

### ISSUE THREAD

**Issue by TB3907** [cosmostation/cosmostation-chrome-extension#327]
How do I undelegate/unstake FET on Cosmostation.io (web-based)? What is the minimun fee (#FET) required? Transferred 3 FET from fetchhub to my Cosmostation wallet - and confirmed on Mintscan - but this transaction is not reflected in the Unbonding amount? Wish to used these Unbonded FET for any transaction fees to unstake existing FET in wallet. Can someone please explain what may be happening? May respond directly to me at TBoenig@gmail.com Thank you.

**Comment by workingabalone** [comment]
Hello @TB3907 A support ticket has been opened for you. Kindly Talk to Cosmos Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by ong-ar** [comment]
You can do it at `https://www.mintscan.io/wallet/stake/?type=unstake`.

**Comment by gonzahiram459-hash** [comment]
trust tramsparency loyal sg1
