### ISSUE TITLE
Support Terra Classic

### ISSUE THREAD

**Issue by niodamian** [cosmostation/cosmostation-chrome-extension#334]
Can you add Terra Classic Network?

**Comment by G-Gamja** [comment]
You can easily add a custom chain using the "Add Custom Chain" option in the side drawer. To add the Terra Classic network, fill out the form with the following information:

- **Custom Chain Name:** Terra Classic
- **REST URL:** https://terra-classic-lcd.publicnode.com
- **Currency Symbol:** LUNC
- **Address Prefix:** terra
- **Denom:** uluna
- **Coin Type:** 330

**Comment by niodamian** [comment]
why is not by default within the wallet ? 
Considering the community - Classic has a huge community around it so will be dizzy people using the costum method as well they might as well face issues with gas fees
